### PR TITLE
Particle library v2 port

### PR DESCRIPTION
**Pull request by derrickrc**
@m-mcgowan thanks for this library!

The version of this library that's uploaded to Particle is outdated and doesn't compile with newer Particle devices: https://docs.particle.io/reference/device-os/libraries/w/WebSockets/

What you have in github though is compatible, so I've just gone ahead reformatted the folder structure to the Particle Library v2 format which should then allow you to update the public library. 

If this looks good, can you please merge and then update your existing WebSockets library (`particle library update`)?

### CODE REVIEW

**Comment by m-mcgowan** [comment]
Hi there! Thanks for doing this. I've not kept up with the particle library revisions, but I'm wondering how we could add a CI build to verify the library sources.  I imagine the `arduino-cli` could be useful here?

**Comment by derrickrc** [comment]
Hmm... I'm afraid I don't have experience with either CI or the `arduino-cli`, what do you have in mind?

My intention here was just to get your WebSocket library working for other folks in the Particle community, but I'm not sure what else this repository is currently feeding into.

**Comment by m-mcgowan** [comment]
Thanks for the work, I appreciate it! I've merged the request, assuming you've tested it already.

If I find the time, I'll circle back and add CI build.

**Comment by derrickrc** [comment]
Thanks! Please also let me know when you've updated your Particle Community Library and I'll test it there with the Web IDE to make sure everything's working as expected.

**Comment by m-mcgowan** [comment]
I've been out of the Particle ecosystem for over 3 years...I'll have to dig in to the docs to figure out how to update the library.  If you know of anyone who would like to take over this project, I'd be happy to pass it over.

**Comment by derrickrc** [comment]
Haha sure... I believe these would be the rough steps:

- Install Particle CLI and login with your particle credentials
- Navigate to the root folder of this newly updated repository on your local machine 
- Run `particle library update`

You might need to change some of the library.json properties to match with what you had previously: https://docs.particle.io/reference/device-os/libraries/w/WebSockets/

If that doesn't work or if it's too much of a headache, don't sweat it - I can go ahead and upload my own updated version of this working library as the owner.

**Pull request merged**
